#!/bin/sh

GREEN='\033[1;32n'
BLUE='\033[1;34m'
NC='\033[0m'

echo
echo -e "${GREEN}Updating ${BLUE}$(hostname)${GREEN}...${NC}"
echo

sudo guix system -L ~/dotfiles reconfigure ~/dotfiles/paulj/systems/$(hostname).scm
