#!/bin/sh
# Navigate to the directory of this script (generally ~/.dotfiles/.bin)
cd "$(dirname "$(readlink -f "$0")")" || exit
cd ..

# The heavy lifting is done by an Emacs script
emacs -Q --script ~/dotfiles/.emacs.d/tangle-dotfiles.el

# Make sure any running Emacs instance gets updated settings
#  emacsclient -e '(load-file "~/.emacs.d/per-system-settings.el")' -a "echo 'Emacs is not currently running'"

# Update configuration symlinks
if [ "$(hostname)" = zeus ]
then
  stow .     # For guix system - stow everything
else         # Otherwise - don't stow the pulseaudio stuff
  stow . \
       -R \
       --ignore=\.config/pulse \
       --ignore=\.config/mimeapps.list \
       --ignore=\.config/dunst \
       --ignore=\.xsession \
       --ignore=\.config/vimb \
       --ignore=\.config/mpv \
       --ignore=\.config/mpd \
       --ignore=\.config/zathura \
       --ignore=\.config/polybar \
       --ignore=\.config/xsettingsd \
       --ignore=\.config/fontconfig
fi

